const doctorsData = [
    {
        name: "Dr. Amit Sharma",
        username: "amitsharma@gmail.com",
        password: "Pass@123",
        speciality: "Cardiologist",
        hospital: "Ruby Hall Clinic",
        experience: "12+ years",
        rating: 4.7,
        fee: 800,
        availability: "Available",
        image: "assets/images/DoctorMale.jpg"
    },
    {
        name: "Dr. Priya Mehta",
        username: "priyamehta@gmail.com",
        password: "Pass@123",
        speciality: "Dermatologist",
        hospital: "Jehangir Hospital",
        experience: "9+ years",
        rating: 4.5,
        fee: 600,
        availability: "Available",
        image: "assets/images/DoctorFeMale.jpg"
    },
    {
        name: "Dr. Rahul Patil",
        username: "rahulpatil@gmail.com",
        password: "Pass@123",
        speciality: "Orthopedic",
        hospital: "Sahyadri Hospital",
        experience: "15+ years",
        rating: 4.8,
        fee: 1000,
        availability: "Busy",
        image: "assets/images/DoctorMale.jpg"
    },
    {
        name: "Dr. Sneha Kulkarni",
        username: "snehakulkarni@gmail.com",
        password: "Pass@123",
        speciality: "Gynecologist",
        hospital: "Aditya Birla Hospital",
        experience: "10+ years",
        rating: 4.6,
        fee: 700,
        availability: "Available",
        image: "assets/images/DoctorFeMale.jpg"
    },
    {
        name: "Dr. Karan Joshi",
        username: "karanjoshi@gmail.com",
        password: "Pass@123",
        speciality: "Neurologist",
        hospital: "Ruby Hall Clinic",
        experience: "14+ years",
        rating: 4.9,
        fee: 1200,
        availability: "Busy",
        image: "assets/images/DoctorMale.jpg"
    },
    {
        name: "Dr. Neha Deshmukh",
        username: "nehadeshmukh@gmail.com",
        password: "Pass@123",
        speciality: "Pediatrician",
        hospital: "Cloudnine Hospital",
        experience: "8+ years",
        rating: 4.4,
        fee: 500,
        availability: "Available",
        image: "assets/images/DoctorFeMale.jpg"
    },
    {
        name: "Dr. Rohan Gupta",
        username: "rohanggupta@gmail.com",
        password: "Pass@123",
        speciality: "Dentist",
        hospital: "Apollo Clinic",
        experience: "11+ years",
        rating: 4.6,
        fee: 400,
        availability: "Available",
        image: "assets/images/DoctorMale.jpg"
    },
    {
        name: "Dr. Pooja Verma",
        username: "poojaverma@gmail.com",
        password: "Pass@123",
        speciality: "ENT Specialist",
        hospital: "Fortis Hospital",
        experience: "13+ years",
        rating: 4.7,
        fee: 750,
        availability: "Busy",
        image: "assets/images/DoctorFeMale.jpg"
    },
    {
        name: "Dr. Vikram Singh",
        username: "vikramsingh@gmail.com",
        password: "Pass@123",
        speciality: "General Physician",
        hospital: "AIIMS",
        experience: "16+ years",
        rating: 4.8,
        fee: 500,
        availability: "Available",
        image: "assets/images/DoctorMale.jpg"
    },
    {
        name: "Dr. Anjali Nair",
        username: "anjalinair@gmail.com",
        password: "Pass@123",
        speciality: "Psychiatrist",
        hospital: "Manipal Hospital",
        experience: "10+ years",
        rating: 4.5,
        fee: 900,
        availability: "Available",
        image: "assets/images/DoctorFeMale.jpg"
    },
    {
        name: "Dr. Suresh Iyer",
        username: "sureshiyer@gmail.com",
        password: "Pass@123",
        speciality: "Oncologist",
        hospital: "Tata Memorial Hospital",
        experience: "18+ years",
        rating: 4.9,
        fee: 1500,
        availability: "Busy",
        image: "assets/images/DoctorMale.jpg"
    },
    {
        name: "Dr. Kavita Shah",
        username: "kavitashah@gmail.com",
        password: "Pass@123",
        speciality: "Endocrinologist",
        hospital: "Hiranandani Hospital",
        experience: "12+ years",
        rating: 4.6,
        fee: 850,
        availability: "Available",
        image: "assets/images/DoctorFeMale.jpg"
    },
    {
        name: "Dr. Arjun Reddy",
        username: "arjunreddy@gmail.com",
        password: "Pass@123",
        speciality: "Pulmonologist",
        hospital: "Care Hospitals",
        experience: "14+ years",
        rating: 4.7,
        fee: 950,
        availability: "Busy",
        image: "assets/images/DoctorMale.jpg"
    },
    {
        name: "Dr. Meera Kapoor",
        username: "meerakapoor@gmail.com",
        password: "Pass@123",
        speciality: "Ophthalmologist",
        hospital: "Eye7 Hospital",
        experience: "9+ years",
        rating: 4.5,
        fee: 600,
        availability: "Available",
        image: "assets/images/DoctorFeMale.jpg"
    },
    {
        name: "Dr. Nitin Agarwal",
        username: "nitinagarwal@gmail.com",
        password: "Pass@123",
        speciality: "Urologist",
        hospital: "Medanta Hospital",
        experience: "17+ years",
        rating: 4.8,
        fee: 1100,
        availability: "Busy",
        image: "assets/images/DoctorMale.jpg"
    },
    {
        name: "Dr. Shweta Joshi",
        username: "shwetajoshi@gmail.com",
        password: "Pass@123",
        speciality: "Radiologist",
        hospital: "Max Healthcare",
        experience: "11+ years",
        rating: 4.6,
        fee: 700,
        availability: "Available",
        image: "assets/images/DoctorFeMale.jpg"
    },
    {
        name: "Dr. Deepak Chavan",
        username: "deepakchavan@gmail.com",
        password: "Pass@123",
        speciality: "Nephrologist",
        hospital: "Kokilaben Hospital",
        experience: "15+ years",
        rating: 4.7,
        fee: 1000,
        availability: "Busy",
        image: "assets/images/DoctorMale.jpg"
    },
    {
        name: "Dr. Ritu Malhotra",
        username: "ritumalhotra@gmail.com",
        password: "Pass@123",
        speciality: "Dietician",
        hospital: "Apollo Hospital",
        experience: "7+ years",
        rating: 4.4,
        fee: 400,
        availability: "Available",
        image: "assets/images/DoctorFeMale.jpg"
    },
    {
        name: "Dr. Manish Yadav",
        username: "manishyadav@gmail.com",
        password: "Pass@123",
        speciality: "Surgeon",
        hospital: "Lilavati Hospital",
        experience: "19+ years",
        rating: 4.9,
        fee: 1300,
        availability: "Busy",
        image: "assets/images/DoctorMale.jpg"
    },
    {
        name: "Dr. Ayesha Khan",
        username: "ayeshakhan@gmail.com",
        password: "Pass@123",
        speciality: "Physiotherapist",
        hospital: "Physiocare Clinic",
        experience: "8+ years",
        rating: 4.5,
        fee: 500,
        availability: "Available",
        image: "assets/images/DoctorFeMale.jpg"
    }
];